### ISSUE TITLE
Add confirmation before starting location import

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/openmrs-module-dhislocation#4]
Under the Administration tab in OpenMRS, the dhis location import starts automatically when you click on the `Import DHIS2 Locations` option under the DhisLocation Connector section. This is a bit risky as someone can accidentally click this by mistake and start the import. When you start the import, it can take 10 minutes or longer for the page to update with the sync results and there's no way to stop the import if you accidentally started it.

It might be good to have a second page where the user confirms they would like to start the input and a warning that it might take several minutes.

**Comment by maimoonak** [comment]
An import management screen added which allows sync from different points, allows to stop sync in middle, shows status of last sync performed, and allows to download sync activity log file

![image](https://user-images.githubusercontent.com/4829880/28556899-bca1787a-7122-11e7-9d7e-aac891df2dc7.png)

**Comment by cafootitt** [comment]
This looks great. Closing.
