### ISSUE TITLE
Add permissions for dhis location import module

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/openmrs-module-dhislocation#5]
It would be good to have permissions for configuring the dhis instance to import locations from and also being able to import the locations from dhis. I think right now anyone with login can import dhis locations.

**Comment by maimoonak** [comment]
The module is now permission protected and is not available to users not having permissions to carry out operations. New permissions added are 'DHIS - Run Syncer' and 'DHIS - Configure'. Release 1.1.0b

**Comment by cafootitt** [comment]
Lgtm.
