### ISSUE TITLE
Fix page warning about leaving the page with unsaved changes

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/openmrs-module-dhislocation#6]
When you change any parameter in the dhis2 configuration settings, you must select save next to each change to save the changes. Even after saving, when you try to leave the page, you get a warning that the page has unsaved changes that will be lost (this is using google chrome browser).

![screen shot 2017-07-20 at 1 47 46 pm](https://user-images.githubusercontent.com/3488986/28414104-bfb563b0-6d52-11e7-8f43-168a3a4c4c0a.png)

I have confirmed that the changes have been saved, because if you ignore the warning and leave the page and go back, the changes are still there.

**Comment by maimoonak** [comment]
Resolved in release 1.1.0b

**Comment by cafootitt** [comment]
Lgtm
